name: voting-app
services:
  vote:
    public: true
    image: okteto.dev/vote
    build: vote
    replicas: 2
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi

  redis:
    image: okteto.dev/redis
    build:
      dockerfile: Dockerfile.redis
    ports:
      - 6379
    resources:
      cpu: 100m
      memory: 128Mi
      storage: 1Gi
    volumes:
      - /data
